<?php
namespace PAW\Core;

enum SubmitStatus: string {
    case NOT_VALID_DNI = 'NOT_VALID_DNI'; 
    case NOT_VALID_NAME = 'NOT_VALID_NAME'; 
    case NOT_VALID_EMAIL = 'NOT_VALID_EMAIL'; 
    case EMAIL_DONT_MATCH = 'EMAIL_DONT_MATCH'; 
    case IS_USED_EMAIL = 'IS_USED_EMAIL'; 
    case IS_USED_DNI = 'IS_USED_DNI'; 
    case NOT_VALID_PASSWORD = 'NOT_VALID_PASSWORD'; 
    case PASSWORD_DONT_MATCH = 'PASSWORD_DONT_MATCH'; 
    case WRONG_PASSWORD = 'WRONG_PASSWORD';
    case NOT_CONFIRMED_TERMS = 'NOT_CONFIRMED_TERMS';
    case NOT_VALID_GENDER = 'NOT_VALID_GENDER';
    case NOT_VALID_BIRTHDATE = 'NOT_VALID_BIRTHDATE';
    case NOT_VALID_AGE = 'NOT_VALID_AGE';
    case NOT_VALID_AGE_OR_BIRTHDATE = 'NOT_VALID_AGE_OR_BIRTHDATE';
    case NOT_VALID_PHONE = 'NOT_VALID_PHONE';
    case NOT_VALID_SPECIALTY = 'NOT_VALID_SPECIALTY';
    case NOT_VALID_PROFESIONAL = 'NOT_VALID_PROFESIONAL';
    case NOT_VALID_SHIFTDATE = 'NOT_VALID_SHIFTDATE';
    case NOT_VALID_SHIFTTIME = 'NOT_VALID_SHIFTTIME';
    case NOT_VALID_SOCIALWORK = 'NOT_VALID_SOCIALWORK';
    case EXCEEDED_FILE_SIZE = 'EXCEEDED_FILE_SIZE';
    case NOT_ALLOWED_FILE_TYPE = 'NOT_ALLOWED_FILE_TYPE';
    case REGISTER_OK = 'REGISTER_OK';
    case LOGIN_OK = 'LOGIN_OK';
    case UPDATE_OK = 'UPDATE_OK';
    case CANCEL_OK = 'CANCEL_OK';
}
?>
